### ISSUE TITLE
No message for missing organization

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#105]
# Issue

No message for missing organization

## Platform info
userId: 6npJx61xNsYlNr0BVLoS5V6XeJf2
buildDate: 20211103104745
sourceVersion: 8acb3a3
platformAppName: instatrail_admin
platformPackageName: 
platformVersion: 1.0.0
platformBuildNumber: 1
platformBuildSignature: 

## Device info
operatingSystem: Web macOS or iOS
appCodeName: Mozilla
appName: Netscape
appVersion: 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
deviceMemory: 8
language: en-GB
languages: [en-GB, en-US, en]
platform: MacIntel
product: Gecko
productSub: 20030107
userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
vendor: Google Inc.
vendorSub: 
maxTouchPoints: 0
hardwareConcurrency: 8

## Screenshot:
![reports/316aca95-0a58-436d-a642-a6abb9e217f6/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/316aca95-0a58-436d-a642-a6abb9e217f6/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/316aca95-0a58-436d-a642-a6abb9e217f6/logs.txt](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/316aca95-0a58-436d-a642-a6abb9e217f6/logs.txt)

**Comment by EXECNOIR** [comment]
issue couldn't be reproduced anymore
