### ISSUE TITLE
History just loading

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#129]
# Issue

History just loading

## Platform info
userId: 6npJx61xNsYlNr0BVLoS5V6XeJf2
buildDate: 20211129104603
sourceVersion: 5091c7f4
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.0.2
platformBuildNumber: 39
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: iPhone 13
model: iPhone
systemName: iOS
utsname: {release: 21.1.0, version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101, machine: arm64, sysname: Darwin, nodename: Janoss-Mac-mini.local}
systemVersion: 15.0
localizedModel: iPhone
identifierForVendor: 7D49E27C-9954-41EE-BD3A-962BFD9ED2DD
isPhysicalDevice: false

## Screenshot:
![reports/fdb9b838-f9d7-4f40-b251-f733f2cd9451/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/fdb9b838-f9d7-4f40-b251-f733f2cd9451/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/fdb9b838-f9d7-4f40-b251-f733f2cd9451/logs.txt](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/fdb9b838-f9d7-4f40-b251-f733f2cd9451/logs.txt)

**Comment by EXECNOIR** [comment]
As of 2021.12.15 I couldn't manage to reproduce the issue.
