### ISSUE TITLE
still hangs while I am trying to enter a trail

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#152]
# Issue

still hangs while I am trying to enter a trail

## Platform info
userId: F3BOp962SUNB6VO1gQO5xqMlIaS2
buildDate: 20220131.1
sourceVersion: 75fb579
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.0.4
platformBuildNumber: 127
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: AkosiPhone
model: iPhone
systemName: iOS
utsname: {release: 21.2.0, version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:43:38 PST 2021; root:xnu-8019.62.2~1/RELEASE_ARM64_T8101, machine: iPhone13,4, sysname: Darwin, nodename: AkosiPhone}
systemVersion: 15.2.1
localizedModel: iPhone
identifierForVendor: D4D795C3-87CC-4680-A310-6D22A0607CF0
isPhysicalDevice: true

## Screenshot:
![reports/364f2e6c-ed66-4d7c-a519-56ef1e2e7b3e/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/364f2e6c-ed66-4d7c-a519-56ef1e2e7b3e/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/364f2e6c-ed66-4d7c-a519-56ef1e2e7b3e/logs.txt](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/364f2e6c-ed66-4d7c-a519-56ef1e2e7b3e/logs.txt)

**Comment by janosroden** [comment]
fixed with
commit fcf0a84be2454a947d8126d8020005469b7ba1ce
Author: Janos Roden <janos.roden@onbased.com>
Date:   Mon Jan 31 11:01:05 2022 +0100

    Fix gql query response stream
