### ISSUE TITLE
Cannot enter to Tram 4-6 Home to Office

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#165]
# Issue

Cannot enter to Tram 4-6 Home to Office

## Platform info
userId: F3BOp962SUNB6VO1gQO5xqMlIaS2
buildDate: 20220214.1
sourceVersion: b7fc3cf
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.0.5
platformBuildNumber: 139
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: AkosiPhone
model: iPhone
systemName: iOS
utsname: {release: 21.3.0, version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:44:48 PST 2022; root:xnu-8019.80.24~23/RELEASE_ARM64_T8101, machine: iPhone13,4, sysname: Darwin, nodename: AkosiPhone}
systemVersion: 15.3
localizedModel: iPhone
identifierForVendor: D4D795C3-87CC-4680-A310-6D22A0607CF0
isPhysicalDevice: true

## Screenshot:
![reports/b56a8dcd-bf03-4697-83b6-5d7140875c5e/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/b56a8dcd-bf03-4697-83b6-5d7140875c5e/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/b56a8dcd-bf03-4697-83b6-5d7140875c5e/logs.txt](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/b56a8dcd-bf03-4697-83b6-5d7140875c5e/logs.txt)

**Comment by janosroden** [comment]
fixed in edit_trail_page branch
