### ISSUE TITLE
Every difficulty is recommended

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#183]
# Issue

Every difficulty is recommended

## Platform info
userId: 6npJx61xNsYlNr0BVLoS5V6XeJf2
buildDate: 20220223090538
sourceVersion: 4f812c2e
platformAppName: instatrail_admin
platformPackageName: 
platformVersion: 1.0.1
platformBuildNumber: 1
platformBuildSignature: 

## Device info
operatingSystem: Web macOS or iOS
appCodeName: Mozilla
appName: Netscape
appVersion: 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36
deviceMemory: 8
language: en-GB
languages: [en-GB, en-US, en]
platform: MacIntel
product: Gecko
productSub: 20030107
userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36
vendor: Google Inc.
vendorSub: 
maxTouchPoints: 0
hardwareConcurrency: 8

## Screenshot:
![reports/def3489d-0b82-4b0e-ab1c-6327910ed6a7/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/def3489d-0b82-4b0e-ab1c-6327910ed6a7/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/def3489d-0b82-4b0e-ab1c-6327910ed6a7/logs.txt](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/def3489d-0b82-4b0e-ab1c-6327910ed6a7/logs.txt)

**Comment by EXECNOIR** [comment]
this seems to be fixed
