### ISSUE TITLE
Wrong numbers on circular trail checkpoints

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#196]
Wrong numbers on circular trail checkpoints

## Platform info
userId: 6npJx61xNsYlNr0BVLoS5V6XeJf2
buildDate: 20220302105833
sourceVersion: 46d7e585
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.0.5
platformBuildNumber: 39
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: iPhone 12 Pro
model: iPhone
systemName: iOS
utsname: {release: 21.3.0, version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101, machine: arm64, sysname: Darwin, nodename: Janoss-Mac-mini.local}
systemVersion: 15.2
localizedModel: iPhone
identifierForVendor: 66D655E1-C96A-4CF6-88EE-CF6CF07623D7
isPhysicalDevice: false

## Screenshot
![reports/d55ad2e8-1bbb-438c-8648-1c7763089c79/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/d55ad2e8-1bbb-438c-8648-1c7763089c79/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/d55ad2e8-1bbb-438c-8648-1c7763089c79/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/d55ad2e8-1bbb-438c-8648-1c7763089c79/logs.1.txt.gz)
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/d55ad2e8-1bbb-438c-8648-1c7763089c79/logs.2.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/d55ad2e8-1bbb-438c-8648-1c7763089c79/logs.2.txt.gz)

**Comment by EXECNOIR** [comment]
Fixed in Apple and Facebook sign in PR (yeah..)
