### ISSUE TITLE
gdpr szempontból 5ös! De miert nem látszik a név azokon a teljesítéseken amit nem Teszt Elek hanem Papp Albert futott? (teszt elek van bejelentkezve)

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#211]
gdpr szempontból 5ös! De miert nem látszik a név azokon a teljesítéseken amit nem Teszt Elek hanem Papp Albert futott? (teszt elek van bejelentkezve)

## Platform info
userId: I9RqKzXvfVbjqdEdMWBWrDjgB6I2
buildDate: 20220412.1
sourceVersion: cac1620
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.1.0
platformBuildNumber: 201
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: papp’s iPhone Xs
model: iPhone
systemName: iOS
utsname: {release: 21.3.0, version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:44:43 PST 2022; root:xnu-8019.80.24~23/RELEASE_ARM64_T8020, machine: iPhone11,6, sysname: Darwin, nodename: papps-iPhone-Xs}
systemVersion: 15.3.1
localizedModel: iPhone
identifierForVendor: B203652C-178F-47B0-8134-0712F81CB5BA
isPhysicalDevice: true

## Screenshot
![reports/fa562fc2-ff2f-41cf-8ae9-22bdd2711570/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/fa562fc2-ff2f-41cf-8ae9-22bdd2711570/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/fa562fc2-ff2f-41cf-8ae9-22bdd2711570/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/fa562fc2-ff2f-41cf-8ae9-22bdd2711570/logs.1.txt.gz)

**Comment by janosroden** [comment]
PR 282
