### ISSUE TITLE
miert m az idő amikor kb 50 secundum óta megyek

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#226]
miert m az idő amikor kb 50 secundum óta megyek

## Platform info
userId: 9ViQ8qkLSNeTSfk6WN5S4SYoFMv1
buildDate: 20220813.1
sourceVersion: cc92505
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.1.3
platformBuildNumber: 267
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: papp’s iPhone Xs
model: iPhone
systemName: iOS
utsname: {release: 21.6.0, version: Darwin Kernel Version 21.6.0: Wed Aug 10 15:38:28 PDT 2022; root:xnu-8020.142.2~1/RELEASE_ARM64_T8020, machine: iPhone11,6, sysname: Darwin, nodename: papps-iPhone-Xs}
systemVersion: 15.6.1
localizedModel: iPhone
identifierForVendor: B203652C-178F-47B0-8134-0712F81CB5BA
isPhysicalDevice: true

## Screenshot
![reports/53c28e76-ef1d-4c2a-b1f6-293c34b37331/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/53c28e76-ef1d-4c2a-b1f6-293c34b37331/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/53c28e76-ef1d-4c2a-b1f6-293c34b37331/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/53c28e76-ef1d-4c2a-b1f6-293c34b37331/logs.1.txt.gz)

**Comment by janosroden** [comment]
commit de7cdb6f20ba4fbde94d7c7dfb8e02f4044b0704
Author: Janos Roden <janos.roden@onbased.com>
Date:   Mon Sep 5 11:22:35 2022 +0200

    Change hun translation: abbrev for sec is 'mp' now
