### ISSUE TITLE
Valamennyi ellenorzo ponton athaladtam, gratulalo uzenetet is kaptam, viszont a turat nem zarta le.

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#233]
Valamennyi ellenorzo ponton athaladtam, gratulalo uzenetet is kaptam, viszont a turat nem zarta le.

## Platform info
userId: Mi5ColbXGPc0X8VOK0oUoViCar33
buildDate: 20220908.1
sourceVersion: a15722a
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.1.3
platformBuildNumber: 278
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: iPhone
model: iPhone
systemName: iOS
utsname: {release: 22.0.0, version: Darwin Kernel Version 22.0.0: Tue Aug 16 20:52:01 PDT 2022; root:xnu-8792.2.11.0.1~1/RELEASE_ARM64_T8101, machine: iPhone13,2, sysname: Darwin, nodename: iPhone-BJ}
systemVersion: 16.0.2
localizedModel: iPhone
identifierForVendor: CE48D01E-9424-4BC8-BBFC-34CD2AAA9B5F
isPhysicalDevice: true

## Screenshot
![reports/7445e449-275d-4bc9-bb32-41c9c0e6cc14/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/7445e449-275d-4bc9-bb32-41c9c0e6cc14/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/7445e449-275d-4bc9-bb32-41c9c0e6cc14/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/7445e449-275d-4bc9-bb32-41c9c0e6cc14/logs.1.txt.gz)

**Comment by defned** [comment]
![308548866_3286306598307875_8122048763146932268_n](https://user-images.githubusercontent.com/4353301/192103507-69bced29-0e7b-4ab7-8e27-82760bad9cc3.jpg)
![308392493_759689015099369_5497825342417249451_n](https://user-images.githubusercontent.com/4353301/192103513-cc584905-3faa-45fd-a6b0-1758e3d16f1b.jpg)

A "Gratuláció"-nál a megadható szöveg nem jelenik meg csak részlegesen.

**Comment by janosroden** [comment]
fixed in fd19a0097e57466092839444c32206bc75ebb77f
