### ISSUE TITLE
Azt írja a térkép hogy még a trail-en vagyok 19 napja, pedig nincs aktiv nevezésem, vagy futás alatt lévő trailem,

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#236]
Azt írja a térkép hogy még a trail-en vagyok 19 napja, pedig nincs aktiv nevezésem, vagy futás alatt lévő trailem,

## Platform info
userId: 9ViQ8qkLSNeTSfk6WN5S4SYoFMv1
buildDate: 20220929.1
sourceVersion: 56a98fb
platformAppName: instatrail_admin
platformPackageName: instatrail_admin
platformVersion: 1.2.0
platformBuildNumber: 1
platformBuildSignature: 

## Device info
operatingSystem: Web macOS or iOS
appCodeName: Mozilla
appName: Netscape
appVersion: 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
deviceMemory: 8
language: en-US
languages: [en-US, en, hu, de]
platform: MacIntel
product: Gecko
productSub: 20030107
userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
vendor: Google Inc.
vendorSub: 
maxTouchPoints: 0
hardwareConcurrency: 10

## Screenshot
![reports/a00bc138-42cd-4cb6-941d-f8833433036f/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/a00bc138-42cd-4cb6-941d-f8833433036f/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/a00bc138-42cd-4cb6-941d-f8833433036f/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/a00bc138-42cd-4cb6-941d-f8833433036f/logs.1.txt.gz)

**Comment by janosroden** [comment]
Fixed in PR 282
