### ISSUE TITLE
Nem látszik a checkpoint teljes neve

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#241]
Nem látszik a checkpoint teljes neve

## Platform info
userId: 6npJx61xNsYlNr0BVLoS5V6XeJf2
buildDate: 20221011.1
sourceVersion: 8ba9e7b
platformAppName: instatrail_admin
platformPackageName: instatrail_admin
platformVersion: 1.2.0
platformBuildNumber: 1
platformBuildSignature: 

## Device info
operatingSystem: Web macOS or iOS
appCodeName: Mozilla
appName: Netscape
appVersion: 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.84
deviceMemory: 8
language: en-GB
languages: [en-GB, en-US, en, hu]
platform: MacIntel
product: Gecko
productSub: 20030107
userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.84
vendor: Google Inc.
vendorSub: 
maxTouchPoints: 0
hardwareConcurrency: 8

## Screenshot
![reports/4474409d-43ba-4b76-8531-cc64b8e3912a/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/4474409d-43ba-4b76-8531-cc64b8e3912a/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/4474409d-43ba-4b76-8531-cc64b8e3912a/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/4474409d-43ba-4b76-8531-cc64b8e3912a/logs.1.txt.gz)

**Comment by palbert75** [comment]
Add  2nd line in this case?
