### ISSUE TITLE
Az infó ablakban a commit hash a pipelines repóból jön, nem a frontendből

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#244]
Az infó ablakban a commit hash a pipelines repóból jön, nem a frontendből

## Platform info
userId: F3BOp962SUNB6VO1gQO5xqMlIaS2
buildDate: 20221011.1
sourceVersion: 8ba9e7b
platformAppName: instatrail_admin
platformPackageName: instatrail_admin
platformVersion: 1.2.0
platformBuildNumber: 1
platformBuildSignature: 

## Device info
operatingSystem: Web macOS or iOS
appCodeName: Mozilla
appName: Netscape
appVersion: 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.84
deviceMemory: 8
language: en-GB
languages: [en-GB]
platform: MacIntel
product: Gecko
productSub: 20030107
userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.84
vendor: Google Inc.
vendorSub: 
maxTouchPoints: 0
hardwareConcurrency: 8

## Screenshot
![reports/efb1469b-2593-437c-8afe-d5a7eb9664a9/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/efb1469b-2593-437c-8afe-d5a7eb9664a9/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/efb1469b-2593-437c-8afe-d5a7eb9664a9/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/efb1469b-2593-437c-8afe-d5a7eb9664a9/logs.1.txt.gz)

**Comment by janosroden** [comment]
fixed
