### ISSUE TITLE
offline modeban hiba

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#252]
offline modeban hiba

## Platform info
userId: 9ViQ8qkLSNeTSfk6WN5S4SYoFMv1
buildDate: 20221124.1
sourceVersion: 3eba9b4
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.2.2
platformBuildNumber: 166549655
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: iPhone
model: iPhone
systemName: iOS
utsname: {release: 22.1.0, version: Darwin Kernel Version 22.1.0: Thu Oct  6 19:34:16 PDT 2022; root:xnu-8792.42.7~1/RELEASE_ARM64_T8120, machine: iPhone15,3, sysname: Darwin, nodename: papps-iPhone-14max}
systemVersion: 16.1
localizedModel: iPhone
identifierForVendor: 5D237455-A403-492D-8A2E-332A99F24A38
isPhysicalDevice: true

## Screenshot
![reports/de5bc053-fae5-4962-bff9-9bb19a75a8ba/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/de5bc053-fae5-4962-bff9-9bb19a75a8ba/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/de5bc053-fae5-4962-bff9-9bb19a75a8ba/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/de5bc053-fae5-4962-bff9-9bb19a75a8ba/logs.1.txt.gz)

**Comment by palbert75** [comment]
Offline modeban nem tudtam elindulni mert ugy tűnik mintha nem kapnánk meg a location updateket.
