### ISSUE TITLE
Language null

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#254]
Language null

## Platform info
userId: 6npJx61xNsYlNr0BVLoS5V6XeJf2
buildDate: 20230203120221
sourceVersion: 4116365c
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.2.3
platformBuildNumber: 39
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: iPhone 14 Pro Max
model: iPhone
systemName: iOS
utsname: {release: 21.6.0, version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101, machine: iPhone15,3, sysname: Darwin, nodename: Janoss-Mac-mini.local}
systemVersion: 16.1
localizedModel: iPhone
identifierForVendor: 88DAD24C-85AE-414C-87B2-BDDAC516C4EB
isPhysicalDevice: false

## Screenshot
![reports/62db265c-3046-47df-94ce-5200207f17c6/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/62db265c-3046-47df-94ce-5200207f17c6/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/62db265c-3046-47df-94ce-5200207f17c6/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/62db265c-3046-47df-94ce-5200207f17c6/logs.1.txt.gz)

**Comment by janosroden** [comment]
Also it switches back and forth on change
