### ISSUE TITLE
anonymouse modban nem jon fel a menu ezert nem lehet elhagyni a profile oldalt

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#288]
anonymouse modban nem jon fel a menu ezert nem lehet elhagyni a profile oldalt

## Platform info
userId: 8OKwx7mj1jc0vsRLw9h1BOwaPHZ2
buildDate: 20230505.2
sourceVersion: 201eabb
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.2.5
platformBuildNumber: 166549808
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: iPhone
model: iPhone
systemName: iOS
utsname: {release: 22.4.0, version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:42:19 PST 2023; root:xnu-8796.102.5~1/RELEASE_ARM64_T8120, machine: iPhone15,3, sysname: Darwin, nodename: papps-iPhone-14max}
systemVersion: 16.4.1
localizedModel: iPhone
identifierForVendor: CBD70639-B548-4EF2-9F77-0BE52729D14B
isPhysicalDevice: true

## Screenshot
![reports/90019b15-91c4-4b44-a111-afcae61bc52c/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/90019b15-91c4-4b44-a111-afcae61bc52c/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/90019b15-91c4-4b44-a111-afcae61bc52c/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/90019b15-91c4-4b44-a111-afcae61bc52c/logs.1.txt.gz)
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/90019b15-91c4-4b44-a111-afcae61bc52c/logs.2.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/90019b15-91c4-4b44-a111-afcae61bc52c/logs.2.txt.gz)
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/90019b15-91c4-4b44-a111-afcae61bc52c/logs.3.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/90019b15-91c4-4b44-a111-afcae61bc52c/logs.3.txt.gz)
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/90019b15-91c4-4b44-a111-afcae61bc52c/logs.4.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/90019b15-91c4-4b44-a111-afcae61bc52c/logs.4.txt.gz)
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/90019b15-91c4-4b44-a111-afcae61bc52c/logs.5.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/90019b15-91c4-4b44-a111-afcae61bc52c/logs.5.txt.gz)

**Comment by palbert75** [comment]
Ide úgy jutottam el, hogy anonymouse modban böngésztem a trail-eket és a regisztrálok gombra kattintottam apple regisztrációval. Az is feltűnt hogy ilyenkor nem jön elő a terms és gdpr szabályzat elfogadása
