### ISSUE TITLE
mi ez a fos?!

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#291]
mi ez a fos?!

## Platform info
userId: JDo3ax72hiWX1QEOQ45GdujRbzV2
buildDate: 20221202.1
sourceVersion: 3eba9b4
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.2.2
platformBuildNumber: 166549786
platformBuildSignature: B3F6372CAEBEA8FED5F8AEBF6A82ED77F29D6A20

## Device info
operatingSystem: IO Android
id: SP1A.210812.016
host: 21DKG923
tags: release-keys
type: user
model: SM-G970F
board: exynos9820
brand: samsung
device: beyond0
product: beyond0lteeea
display: SP1A.210812.016.G970FXXSGHWC1
hardware: exynos9820
bootloader: G970FXXSGHWC1
version: {baseOS: samsung/beyond0lteeea/beyond0:12/SP1A.210812.016/G970FXXUGHVJ5:user/release-keys, sdkInt: 31, release: 12, codename: REL, incremental: G970FXXSGHWC1, previewSdkInt: 0, securityPatch: 2023-03-01}
fingerprint: samsung/beyond0lteeea/beyond0:12/SP1A.210812.016/G970FXXSGHWC1:user/release-keys
manufacturer: samsung
supportedAbis: [arm64-v8a, armeabi-v7a, armeabi]
systemFeatures: [android.hardware.sensor.proximity, com.samsung.android.sdk.camera.processor, com.samsung.feature.aodservice_v09, com.sec.feature.motionrecognition_service, com.sec.feature.cover.sview, android.hardware.telephony.ims.singlereg, android.hardware.sensor.accelerometer, android.software.controls, android.hardware.faketouch, android.hardware.usb.accessory, android.software.backup, android.hardware.touchscreen, android.hardware.touchscreen.multitouch, android.software.print, android.software.activities_on_secondary_displays, com.sec.feature.nfc_authentication_cover, com.samsung.feature.SAMSUNG_EXPERIENCE, com.sec.feature.nfc_authentication, android.software.voice_recognizers, android.software.picture_in_picture, android.hardware.fingerprint, com.samsung.android.knox.knoxsdk, android.hardware.sensor.gyroscope, android.hardware.audio.low_latency, android.software.vulkan.deqp.level, android.software.cant_save_state, android.hardware.security.model.compatible, com.samsung.feature.device_category_phone, com.samsung.android.authfw.tahal, android.hardware.opengles.aep, com.sec.feature.sensorhub, android.hardware.bluetooth, android.hardware.camera.autofocus, android.hardware.telephony.gsm, android.hardware.telephony.ims, com.sec.feature.cocktailpanel, com.samsung.android.bio.face, android.software.sip.voip, android.hardware.se.omapi.ese, android.software.opengles.deqp.level, com.sec.feature.saccessorymanager, com.samsung.feature.samsung_experience_mobile, com.samsung.android.camerasdkservice, android.hardware.camera.concurrent, android.hardware.usb.host, android.hardware.audio.output, android.software.verified_boot, android.hardware.camera.flash, android.hardware.camera.front, android.hardware.sensor.hifi_sensors, android.hardware.se.omapi.uicc, android.hardware.screen.portrait, com.google.android.feature.DPS, android.hardware.nfc, com.google.android.feature.TURBO_PRELOAD, com.samsung.feature.ipsgeofence, com.nxp.mifare, com.sec.feature.cover.clearcover, android.hardware.sensor.stepdetector, android.software.home_screen, com.sec.feature.cover.ledbackcover, android.hardware.microphone, com.samsung.feature.aremoji.v2, android.software.autofill, com.samsung.android.sdk.camera.processor.effect, android.software.securely_removes_users, android.hardware.bluetooth_le, android.hardware.sensor.compass, android.hardware.touchscreen.multitouch.jazzhand, android.hardware.sensor.barometer, android.software.app_widgets, android.software.input_methods, android.hardware.sensor.light, android.hardware.vulkan.version, android.software.companion_device_setup, com.samsung.feature.galaxyfinder_v7, com.sec.feature.wirelesscharger_authentication, android.software.device_admin, android.hardware.keystore.limited_use_key, android.hardware.wifi.passpoint, android.hardware.camera, android.hardware.screen.landscape, android.hardware.ram.normal, com.samsung.feature.samsungpositioning.snlp, com.samsung.android.authfw, com.samsung.android.api.version.2402, com.samsung.android.api.version.2403, com.samsung.android.api.version.2501, com.samsung.android.api.version.2502, com.samsung.android.api.version.2601, com.samsung.android.api.version.2701, com.samsung.android.api.version.2801, com.samsung.android.api.version.2802, com.samsung.android.api.version.2803, com.samsung.android.api.version.2901, com.samsung.android.api.version.2902, com.samsung.android.api.version.2903, com.samsung.android.api.version.3001, com.samsung.android.api.version.3002, com.samsung.android.api.version.3101, com.sec.feature.cover, android.software.managed_users, com.sec.feature.nsflp, android.software.webview, android.hardware.sensor.stepcounter, android.hardware.camera.capability.manual_post_processing, android.hardware.camera.any, android.hardware.camera.capability.raw, android.hardware.vulkan.compute, android.software.connectionservice, android.hardware.touchscreen.multitouch.distinct, android.hardware.location.network, android.hardware.camera.ar, com.sec.android.secimaging, android.software.cts, android.software.sip, android.hardware.camera.capability.manual_sensor, android.software.app_enumeration, android.hardware.camera.level.full, com.sec.feature.usb_authentication, com.google.android.feature.EEA_DEVICE, android.hardware.wifi.direct, android.software.live_wallpaper, com.sec.feature.pocketmode, android.software.ipsec_tunnels, com.google.android.paid.chrome, android.software.freeform_window_management, android.hardware.audio.pro, android.hardware.nfc.hcef, android.hardware.nfc.uicc, android.hardware.location.gps, android.software.midi, com.samsung.feature.samsungpositioning, android.hardware.nfc.any, android.hardware.nfc.ese, android.hardware.nfc.hce, android.hardware.wifi, android.hardware.location, com.google.android.paid.search, android.hardware.vulkan.level, com.sec.feature.cover.flip, com.samsung.android.cameraxservice, com.samsung.android.knox.knoxsdk.api.level.33, com.samsung.android.knox.knoxsdk.api.level.34, com.samsung.android.knox.knoxsdk.api.level.35, android.hardware.wifi.aware, android.software.secure_lock_screen, com.sec.feature.cover.nfcledcover, android.hardware.telephony, com.sec.android.smartface.smart_stay, android.software.file_based_encryption, null]
isPhysicalDevice: true
supported32BitAbis: [armeabi-v7a, armeabi]
supported64BitAbis: [arm64-v8a]

## Screenshot
![reports/3cdb98b6-0ccf-4e7e-b02f-7f72f99a82b7/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/3cdb98b6-0ccf-4e7e-b02f-7f72f99a82b7/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/3cdb98b6-0ccf-4e7e-b02f-7f72f99a82b7/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/3cdb98b6-0ccf-4e7e-b02f-7f72f99a82b7/logs.1.txt.gz)
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/3cdb98b6-0ccf-4e7e-b02f-7f72f99a82b7/logs.2.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/3cdb98b6-0ccf-4e7e-b02f-7f72f99a82b7/logs.2.txt.gz)

**Comment by janosroden** [comment]
1.2.2 was released on December 2

**Comment by defned** [comment]
Igen eszembe jutott
________________________________
