### ISSUE TITLE
each entrie is given up still visible in the entrie list. Maybe they should be in history filterable?

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#30]
each entrie is given up still visible in the entrie list. Maybe they should be in history filterable?

![screenshot-94475020-8055-45d2-bffb-f083ab7105a3](https://raw.githubusercontent.com/onbased/InstaTrail/main/screenshot-94475020-8055-45d2-bffb-f083ab7105a3)

**Comment by Pali15** [comment]
Resolved
