### ISSUE TITLE
Elevation calculation bug?

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#300]
Elevation calculation bug?

## Platform info
userId: xxPSIri5NoZdaXloXqNpFVIoXLS2
buildDate: 20230602.1
sourceVersion: 201eabb
platformAppName: instatrail_admin
platformPackageName: instatrail_admin
platformVersion: 1.2.5
platformBuildNumber: 1
platformBuildSignature: 

## Device info
operatingSystem: Web macOS or iOS
appCodeName: Mozilla
appName: Netscape
appVersion: 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
deviceMemory: null
language: en-GB
languages: [en-GB]
platform: MacIntel
product: Gecko
productSub: 20030107
userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
vendor: Apple Computer, Inc.
vendorSub: 
maxTouchPoints: 0
hardwareConcurrency: 8

## Screenshot
![reports/4eb4e6e6-fbd7-4474-ba60-45eb9554e7b2/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/4eb4e6e6-fbd7-4474-ba60-45eb9554e7b2/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/4eb4e6e6-fbd7-4474-ba60-45eb9554e7b2/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/4eb4e6e6-fbd7-4474-ba60-45eb9554e7b2/logs.1.txt.gz)

**Comment by janosroden** [comment]
Fixed in PR486
