### ISSUE TITLE
ahol nincs kép a checkpointnál ott mobilon nagy fehér képernyő ami blokkol teljesen!

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#301]
ahol nincs kép a checkpointnál ott mobilon nagy fehér képernyő ami blokkol teljesen!

## Platform info
userId: F3BOp962SUNB6VO1gQO5xqMlIaS2
buildDate: 20230619.1
sourceVersion: 201eabb
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.2.8
platformBuildNumber: 166549813
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: iPhone
model: iPhone
systemName: iOS
utsname: {release: 22.5.0, version: Darwin Kernel Version 22.5.0: Mon Apr 24 21:09:28 PDT 2023; root:xnu-8796.122.4~1/RELEASE_ARM64_T8120, machine: iPhone15,3, sysname: Darwin, nodename: Akos-iPhone-14-Pro-Max}
systemVersion: 16.5
localizedModel: iPhone
identifierForVendor: 748F204F-9E9D-43EB-B97C-7456329DB6D5
isPhysicalDevice: true

## Screenshot
![reports/eb55b7e8-db94-4766-a086-576a76661d69/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/eb55b7e8-db94-4766-a086-576a76661d69/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/eb55b7e8-db94-4766-a086-576a76661d69/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/eb55b7e8-db94-4766-a086-576a76661d69/logs.1.txt.gz)
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/eb55b7e8-db94-4766-a086-576a76661d69/logs.2.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/eb55b7e8-db94-4766-a086-576a76661d69/logs.2.txt.gz)
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/eb55b7e8-db94-4766-a086-576a76661d69/logs.3.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/eb55b7e8-db94-4766-a086-576a76661d69/logs.3.txt.gz)

**Comment by EXECNOIR** [comment]
seems good
