### ISSUE TITLE
nearby trails not visible after first install

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#326]
nearby trails not visible after first install

## Platform info
userId: 8OKwx7mj1jc0vsRLw9h1BOwaPHZ2
buildDate: $(date +%Y%m%d%H%M%S)
sourceVersion: $(git rev-parse --short HEAD)
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.2.17
platformBuildNumber: 39
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
systemName: iOS
isPhysicalDevice: true
utsname: {release: 23.2.0, sysname: Darwin, nodename: localhost, machine: iPhone15,3, version: Darwin Kernel Version 23.2.0: Sun Nov 12 06:35:16 PST 2023; root:xnu-10002.60.75.0.3~27/RELEASE_ARM64_T8120}
model: iPhone
localizedModel: iPhone
systemVersion: 17.2.1
name: iPhone
identifierForVendor: 9A42008A-D5F4-4498-8643-17F3BF718F86

## Screenshot
![reports/a10a2ec2-8bb8-4bea-bc37-97b3819121e3/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/a10a2ec2-8bb8-4bea-bc37-97b3819121e3/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/a10a2ec2-8bb8-4bea-bc37-97b3819121e3/logs.1.txt.gz](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/a10a2ec2-8bb8-4bea-bc37-97b3819121e3/logs.1.txt.gz)

**Comment by janosroden** [comment]
Fixed in PR482
