### ISSUE TITLE
Can not create trail

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#42]
Can not create trail

![screenshot-dc97c4e7-d852-453a-bc5a-8a85d4063898](https://raw.githubusercontent.com/onbased/InstaTrail/main/screenshot-dc97c4e7-d852-453a-bc5a-8a85d4063898)

**Comment by palbert75** [comment]
[TurULTRAil-végleges (2).zip](https://github.com/onbased/InstaTrail/files/7208512/TurULTRAil-vegleges.2.zip)
