### ISSUE TITLE
After being in backgriund for a while this awaitad me when I came back to the application

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#58]
After being in backgriund for a while this awaitad me when I came back to the application

==========================
platform: io iOS, userId: 9ViQ8qkLSNeTSfk6WN5S4SYoFMv1

 build version: c25dc51 build date: 20210923.1 version: 1.0.0+16 ![screenshot-5129440a-b145-4baa-ad68-f7a74a074632](https://raw.githubusercontent.com/onbased/InstaTrail/main/screenshot-5129440a-b145-4baa-ad68-f7a74a074632)

![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [logs-b8544325-53d7-4ba9-9037-8f8e2390773a.txt](https://raw.githubusercontent.com/onbased/InstaTrail/main/logs-b8544325-53d7-4ba9-9037-8f8e2390773a.txt)

**Comment by EXECNOIR** [comment]
According to the author of the issue this is not an issue anymore.
