### ISSUE TITLE
No trails are visible (infinit ptogress indicator)

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#73]
# Issue

No trails are visible (infinit ptogress indicator)

## Platform info
userId: 9ViQ8qkLSNeTSfk6WN5S4SYoFMv1
buildDate: 20211006.3
sourceVersion: 9932823
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.0.0
platformBuildNumber: 26
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: papp’s iPhone Xs
model: iPhone
systemName: iOS
utsname: {release: 20.6.0, version: Darwin Kernel Version 20.6.0: Mon Jun 21 21:23:37 PDT 2021; root:xnu-7195.140.42~10/RELEASE_ARM64_T8020, machine: iPhone11,6, sysname: Darwin, nodename: papps-iPhone-Xs}
systemVersion: 14.7.1
localizedModel: iPhone
identifierForVendor: C49B5FC2-1E1F-45E4-97BC-AA21129E2666
isPhysicalDevice: true

## Screenshot:
![reports/38dabecc-71d7-44ac-a93f-2ce1c9ca6a69/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/38dabecc-71d7-44ac-a93f-2ce1c9ca6a69/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/38dabecc-71d7-44ac-a93f-2ce1c9ca6a69/logs.txt](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/38dabecc-71d7-44ac-a93f-2ce1c9ca6a69/logs.txt)

**Comment by janosroden** [comment]
@palbert75 What is the problem exactly? Or they appeared just before you hit send button?
According log your phone was busy to send location points to the server.
