### ISSUE TITLE
offline?

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#75]
# Issue

offline?

## Platform info
userId: Gs1AEmym08e1dUdmWmvw5f6Gezs2
buildDate: 20211006.3
sourceVersion: 9932823
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.0.0
platformBuildNumber: 26
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: Ákos iPhone
model: iPhone
systemName: iOS
utsname: {release: 21.0.0, version: Darwin Kernel Version 21.0.0: Sun Aug 15 20:55:58 PDT 2021; root:xnu-8019.12.5~1/RELEASE_ARM64_T8101, machine: iPhone13,4, sysname: Darwin, nodename: Akos-iPhone}
systemVersion: 15.0
localizedModel: iPhone
identifierForVendor: D4D795C3-87CC-4680-A310-6D22A0607CF0
isPhysicalDevice: true

## Screenshot:
![reports/7176e733-e0bd-4234-9881-f1dfe429206b/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/7176e733-e0bd-4234-9881-f1dfe429206b/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/7176e733-e0bd-4234-9881-f1dfe429206b/logs.txt](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/7176e733-e0bd-4234-9881-f1dfe429206b/logs.txt)

**Comment by EXECNOIR** [comment]
As of 2021.12.15. seems not to be an issue anymore.
