### ISSUE TITLE
Valahogy egyértelművé kellene tenni hol a rajt/cél a turakon igazából ha kört futunk akkor indulas előtt eleg a start ot kirakni indulas utan mar csak a cél relevans talán vagy egymás alá/felé kirakni ?

### ISSUE THREAD

**Issue by defned** [onbased/InstaTrail#87]
# Issue

Valahogy egyértelművé kellene tenni hol a rajt/cél a turakon igazából ha kört futunk akkor indulas előtt eleg a start ot kirakni indulas utan mar csak a cél relevans talán vagy egymás alá/felé kirakni ?

## Platform info
userId: 9ViQ8qkLSNeTSfk6WN5S4SYoFMv1
buildDate: 20211016.1
sourceVersion: 2fa250b
platformAppName: InstaTrail
platformPackageName: com.onbased.instatrail
platformVersion: 1.0.0
platformBuildNumber: 33
platformBuildSignature: 

## Device info
operatingSystem: IO iOS
name: papp’s iPhone Xs
model: iPhone
systemName: iOS
utsname: {release: 20.6.0, version: Darwin Kernel Version 20.6.0: Mon Jun 21 21:23:37 PDT 2021; root:xnu-7195.140.42~10/RELEASE_ARM64_T8020, machine: iPhone11,6, sysname: Darwin, nodename: papps-iPhone-Xs}
systemVersion: 14.7.1
localizedModel: iPhone
identifierForVendor: C49B5FC2-1E1F-45E4-97BC-AA21129E2666
isPhysicalDevice: true

## Screenshot:
![reports/5b65f9bc-eb77-4309-b96b-71c25392674c/screenshot.png](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/5b65f9bc-eb77-4309-b96b-71c25392674c/screenshot.png)

## Logs:
![File Icon](https://raw.githubusercontent.com/onbased/InstaTrail/main/texticon.svg) [reports/5b65f9bc-eb77-4309-b96b-71c25392674c/logs.txt](https://raw.githubusercontent.com/onbased/InstaTrail/main/reports/5b65f9bc-eb77-4309-b96b-71c25392674c/logs.txt)

**Comment by EXECNOIR** [comment]
this is not an issue in the current version. (2021.12.15.)
